# Redpanda Dockerfile
FROM docker.redpanda.com/redpandadata/redpanda:latest

# Set environment variables for Redpanda
ENV REDPANDA_AUTO_CREATE_TOPICS=true \
    REDPANDA_ENABLE_IDEMPOTENCE=true \
    REDPANDA_ENABLE_TRANSACTIONS=true \
    REDPANDA_TRANSACTION_TIMEOUT_MS=60000 \
    REDPANDA_ABORT_INDEX_SEGMENT_SIZE=1073741824 \
    REDPANDA_LOG_RETENTION_BYTES=-1 \
    REDPANDA_LOG_RETENTION_HOURS=168 \
    REDPANDA_SEGMENT_SIZE=536870912 \
    REDPANDA_COMPACTED_LOG_SEGMENT_SIZE=67108864 \
    REDPANDA_MAX_COMPACTION_LAG_MS=9223372036854775807 \
    REDPANDA_GROUP_TOPIC_PARTITIONS=16 \
    REDPANDA_FETCH_MAX_BYTES=57671680 \
    REDPANDA_MAX_PARTITION_FETCH_BYTES=1048576 \
    REDPANDA_DEFAULT_TOPIC_REPLICATION=1 \
    REDPANDA_DEFAULT_TOPIC_PARTITIONS=1 \
    REDPANDA_ENABLE_SASL=false \
    REDPANDA_ENABLE_TLS=false \
    REDPANDA_ENABLE_CONSOLE=true

# Expose ports
EXPOSE 9092 9093 9644 8080 8081 8082

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=5 \
    CMD rpk cluster health | grep -q 'Healthy' || exit 1

# Default command
CMD ["redpanda", "start", "--mode", "dev-container"]
